# 단어 임베딩

In [88]:
word2index={'apple':0, 'ant':1, 'bee':2, 'boat':3, 'coat':4}

In [89]:
target='ant'

In [90]:
from collections import Counter
import math

In [95]:
target_index = word2index['ant']
scores = Counter()

In [92]:
import numpy as np

In [93]:
weights = np.random.random((len(word2index), 4))
weights

array([[0.20190222, 0.06795419, 0.48916547, 0.81759118],
       [0.99995407, 0.5689621 , 0.19120696, 0.89552894],
       [0.16982509, 0.77327364, 0.20678282, 0.81214786],
       [0.59222641, 0.39227607, 0.81182571, 0.8347283 ],
       [0.20574101, 0.40657882, 0.52024495, 0.77814558]])

In [100]:
for word, index in word2index.items():
    raw_difference = weights[index] - weights[target_index]
    print(weights[index], weights[target_index])
    print('-' * 20)
    print('raw_difference:', raw_difference)
    print('-' * 20)
    
    squared_difference = raw_difference * raw_difference
    print('squared_difference:', squared_difference)
    print('-' * 20)
    
    scores[word] = -math.sqrt(sum(squared_difference))
    print('scores:', scores)
    print()
    
    if index < len(word2index) - 1:
        print('<next>')

[0.20190222 0.06795419 0.48916547 0.81759118] [0.99995407 0.5689621  0.19120696 0.89552894]
--------------------
raw_difference: [-0.79805185 -0.50100791  0.29795851 -0.07793776]
--------------------
squared_difference: [0.63688675 0.25100893 0.08877927 0.00607429]
--------------------
scores: Counter({'ant': -0.0, 'boat': -0.7657180621863027, 'bee': -0.8590997188427038, 'coat': -0.8827160171571931, 'apple': -0.9913370994397364})

<next>
[0.99995407 0.5689621  0.19120696 0.89552894] [0.99995407 0.5689621  0.19120696 0.89552894]
--------------------
raw_difference: [0. 0. 0. 0.]
--------------------
squared_difference: [0. 0. 0. 0.]
--------------------
scores: Counter({'ant': -0.0, 'boat': -0.7657180621863027, 'bee': -0.8590997188427038, 'coat': -0.8827160171571931, 'apple': -0.9913370994397364})

<next>
[0.16982509 0.77327364 0.20678282 0.81214786] [0.99995407 0.5689621  0.19120696 0.89552894]
--------------------
raw_difference: [-0.83012897  0.20431153  0.01557586 -0.08338108]
-----